# Defrag:
#  https://github.com/NullVoxPopuli/defrag

# When writing to package.json,
# remove the semver-range, pinning the dependencie
# to an exact version.
#
# Possible values:
#  pinned
#  patches
#  minors
write-as: pinned

overrides:
  - path: packages/*/addon/package.json
    devDependencies: pinned
    dependencies: minors 
  - path: packages/syntax/**/*
    devDependencies: false
    dependencies: false 

update-range:
  "~":
    - cm-buildhelper 
    - "@codemirror/*" 
    - "@lezer/*"
    - "rollup"
