packages:
  - './dev'
  ####################################
  #
  # Apps 
  #
  ####################################
  - './apps/*'
  ####################################
  #
  # Libraries, Addons, Test Apps 
  #
  ####################################
  - './packages/*'
  - './packages/*/addon'
  - './packages/*/test-app'
  - './packages/repl-sdk/tests-self'
  - './packages/app-support/*'
  - './packages/app-support/*/addon'
  - './packages/app-support/*/test-app'
  ####################################
  #
  # Codemirror + Lezer 
  #
  ####################################
  - './packages/syntax/*'
  # packages/syntax / { syntax name } / { codemirror, lezer } 
  - './packages/syntax/*/*'
  - './packages/syntax/*/*/dev'
  - './packages/syntax/*/*/tests'
  ####################################
  #
  # Experiments
  #
  ####################################
  - './spikes/**'
