export const tmpData = {
  list: [
    [
      {
        path: '/1-introduction/1-basics',
        name: '1-basics',
        groupName: 'introduction',
        tutorialName: 'basics',
      },
      {
        path: '/1-introduction/2-adding-data',
        name: '2-adding-data',
        groupName: 'introduction',
        tutorialName: 'addingdata',
      },
      {
        path: '/1-introduction/3-transforming-data',
        name: '3-transforming-data',
        groupName: 'introduction',
        tutorialName: 'transformingdata',
      },
      {
        path: '/1-introduction/4-multiple-transforms',
        name: '4-multiple-transforms',
        groupName: 'introduction',
        tutorialName: 'multipletransforms',
      },
      {
        path: '/1-introduction/5-dynamic-attributes',
        name: '5-dynamic-attributes',
        groupName: 'introduction',
        tutorialName: 'dynamicattributes',
      },
      {
        path: '/1-introduction/6-browser-utilities',
        name: '6-browser-utilities',
        groupName: 'introduction',
        tutorialName: 'browserutilities',
      },
    ],
    [
      {
        path: '/2-reactivity/1-values',
        name: '1-values',
        groupName: 'reactivity',
        tutorialName: 'values',
      },
      {
        path: '/2-reactivity/2-decorated-values',
        name: '2-decorated-values',
        groupName: 'reactivity',
        tutorialName: 'decoratedvalues',
      },
      {
        path: '/2-reactivity/3-derived-values',
        name: '3-derived-values',
        groupName: 'reactivity',
        tutorialName: 'derivedvalues',
      },
      {
        path: '/2-reactivity/4-functions',
        name: '4-functions',
        groupName: 'reactivity',
        tutorialName: 'functions',
      },
      {
        path: '/2-reactivity/5-resources',
        name: '5-resources',
        groupName: 'reactivity',
        tutorialName: 'resources',
      },
      {
        path: '/2-reactivity/6-resource-builders',
        name: '6-resource-builders',
        groupName: 'reactivity',
        tutorialName: 'resourcebuilders',
      },
      {
        path: '/2-reactivity/6-resource-composition',
        name: '6-resource-composition',
        groupName: 'reactivity',
        tutorialName: 'resourcecomposition',
      },
      {
        path: '/2-reactivity/7-modifiers',
        name: '7-modifiers',
        groupName: 'reactivity',
        tutorialName: 'modifiers',
      },
      {
        path: '/2-reactivity/8-components',
        name: '8-components',
        groupName: 'reactivity',
        tutorialName: 'components',
      },
      {
        path: '/2-reactivity/9-components-with-state',
        name: '9-components-with-state',
        groupName: 'reactivity',
        tutorialName: 'componentswithstate',
      },
    ],
    [
      {
        path: '/3-event-handling/1-dom-events',
        name: '1-dom-events',
        groupName: 'eventhandling',
        tutorialName: 'domevents',
      },
      {
        path: '/3-event-handling/2-event-modifiers',
        name: '2-event-modifiers',
        groupName: 'eventhandling',
        tutorialName: 'eventmodifiers',
      },
      {
        path: '/3-event-handling/3-dom-event-forwarding',
        name: '3-dom-event-forwarding',
        groupName: 'eventhandling',
        tutorialName: 'domeventforwarding',
      },
      {
        path: '/3-event-handling/4-custom-events',
        name: '4-custom-events',
        groupName: 'eventhandling',
        tutorialName: 'customevents',
      },
    ],
    [
      {
        path: '/4-logic/1-if-blocks',
        name: '1-if-blocks',
        groupName: 'logic',
        tutorialName: 'ifblocks',
      },
      {
        path: '/4-logic/2-else-blocks',
        name: '2-else-blocks',
        groupName: 'logic',
        tutorialName: 'elseblocks',
      },
      {
        path: '/4-logic/3-else-if-blocks',
        name: '3-else-if-blocks',
        groupName: 'logic',
        tutorialName: 'elseifblocks',
      },
      {
        path: '/4-logic/4-inline-if',
        name: '4-inline-if',
        groupName: 'logic',
        tutorialName: 'inlineif',
      },
      {
        path: '/4-logic/5-each-blocks',
        name: '5-each-blocks',
        groupName: 'logic',
        tutorialName: 'eachblocks',
      },
      {
        path: '/4-logic/6-each-in-blocks',
        name: '6-each-in-blocks',
        groupName: 'logic',
        tutorialName: 'eachinblocks',
      },
      {
        path: '/4-logic/7-keyed-each-blocks',
        name: '7-keyed-each-blocks',
        groupName: 'logic',
        tutorialName: 'keyedeachblocks',
      },
      {
        path: '/4-logic/8-let-blocks',
        name: '8-let-blocks',
        groupName: 'logic',
        tutorialName: 'letblocks',
      },
      {
        path: '/4-logic/9-portalling',
        name: '9-portalling',
        groupName: 'logic',
        tutorialName: 'portalling',
      },
      {
        path: '/4-logic/10-unless-blocks',
        name: '10-unless-blocks',
        groupName: 'logic',
        tutorialName: 'unlessblocks',
      },
    ],
    [
      {
        path: '/5-builtins/1-array',
        name: '1-array',
        groupName: 'builtins',
        tutorialName: 'array',
      },
      {
        path: '/5-builtins/2-hash',
        name: '2-hash',
        groupName: 'builtins',
        tutorialName: 'hash',
      },
      {
        path: '/5-builtins/3-htmlSafe',
        name: '3-htmlSafe',
        groupName: 'builtins',
        tutorialName: 'htmlSafe',
      },
    ],
    [
      {
        path: '/6-partial-application/1-fn',
        name: '1-fn',
        groupName: 'partialapplication',
        tutorialName: 'fn',
      },
      {
        path: '/6-partial-application/2-helper',
        name: '2-helper',
        groupName: 'partialapplication',
        tutorialName: 'helper',
      },
      {
        path: '/6-partial-application/3-modifier',
        name: '3-modifier',
        groupName: 'partialapplication',
        tutorialName: 'modifier',
      },
      {
        path: '/6-partial-application/4-component',
        name: '4-component',
        groupName: 'partialapplication',
        tutorialName: 'component',
      },
      {
        path: '/6-partial-application/5-component-attributes',
        name: '5-component-attributes',
        groupName: 'partialapplication',
        tutorialName: 'componentattributes',
      },
      {
        path: '/6-partial-application/6-component-modifiers',
        name: '6-component-modifiers',
        groupName: 'partialapplication',
        tutorialName: 'componentmodifiers',
      },
    ],
    [
      {
        path: '/7-form-data/1-automatic-binding',
        name: '1-automatic-binding',
        groupName: 'formdata',
        tutorialName: 'automaticbinding',
      },
      {
        path: '/7-form-data/2-initial-data',
        name: '2-initial-data',
        groupName: 'formdata',
        tutorialName: 'initialdata',
      },
      {
        path: '/7-form-data/3-non-string-data-types',
        name: '3-non-string-data-types',
        groupName: 'formdata',
        tutorialName: 'nonstringdatatypes',
      },
    ],
    [
      {
        path: '/9-component-patterns/0-template-only',
        name: '0-template-only',
        groupName: 'componentpatterns',
        tutorialName: 'templateonly',
      },
      {
        path: '/9-component-patterns/1-class-component',
        name: '1-class-component',
        groupName: 'componentpatterns',
        tutorialName: 'classcomponent',
      },
      {
        path: '/9-component-patterns/2-block-content',
        name: '2-block-content',
        groupName: 'componentpatterns',
        tutorialName: 'blockcontent',
      },
      {
        path: '/9-component-patterns/2-multiple-blocks',
        name: '2-multiple-blocks',
        groupName: 'componentpatterns',
        tutorialName: 'multipleblocks',
      },
      {
        path: '/9-component-patterns/3-conditional-blocks',
        name: '3-conditional-blocks',
        groupName: 'componentpatterns',
        tutorialName: 'conditionalblocks',
      },
      {
        path: '/9-component-patterns/4-contextual-components',
        name: '4-contextual-components',
        groupName: 'componentpatterns',
        tutorialName: 'contextualcomponents',
      },
      {
        path: '/9-component-patterns/5-provider-components',
        name: '5-provider-components',
        groupName: 'componentpatterns',
        tutorialName: 'providercomponents',
      },
      {
        path: '/9-component-patterns/6-provider-components-too',
        name: '6-provider-components-too',
        groupName: 'componentpatterns',
        tutorialName: 'providercomponentstoo',
      },
      {
        path: '/9-component-patterns/7-dynamically-chosen-component',
        name: '7-dynamically-chosen-component',
        groupName: 'componentpatterns',
        tutorialName: 'dynamicallychosencomponent',
      },
      {
        path: '/9-component-patterns/8-arg-components',
        name: '8-arg-components',
        groupName: 'componentpatterns',
        tutorialName: 'argcomponents',
      },
      {
        path: '/9-component-patterns/9-portalling',
        name: '9-portalling',
        groupName: 'componentpatterns',
        tutorialName: 'portalling',
      },
    ],
    [
      {
        path: '/11-requesting-data/1-using-remote-data',
        name: '1-using-remote-data',
        groupName: 'requestingdata',
        tutorialName: 'usingremotedata',
      },
    ],
    [
      {
        path: '/12-loading-patterns/1-keeping-latest',
        name: '1-keeping-latest',
        groupName: 'loadingpatterns',
        tutorialName: 'keepinglatest',
      },
    ],
    [
      {
        path: '/13-managing-state/1-shared-state',
        name: '1-shared-state',
        groupName: 'managingstate',
        tutorialName: 'sharedstate',
      },
      {
        path: '/13-managing-state/2-localStorage',
        name: '2-localStorage',
        groupName: 'managingstate',
        tutorialName: 'localStorage',
      },
    ],
    [
      {
        path: '/20-web-components/2-ionic-toggle',
        name: '2-ionic-toggle',
        groupName: 'webcomponents',
        tutorialName: 'ionictoggle',
      },
    ],
    [
      {
        path: '/99-next-steps/1-congratulations',
        name: '1-congratulations',
        groupName: 'nextsteps',
        tutorialName: 'congratulations',
      },
    ],
    [],
    [],
    [],
    [],
    [
      {
        path: '/x-resources/x-services',
        name: 'x-services',
        groupName: 'xresources',
        tutorialName: 'xservices',
      },
    ],
  ],
};
