name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm

      - run: git fetch origin --depth 1    
      - run: git checkout origin/main -- pnpm-lock.yaml
      - run: pnpm install --fix-lockfile
      - run: pnpm lint:fix

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
